### ISSUE TITLE
spammers need to die

### ISSUE THREAD

**Issue by rivetgeek** [IcaroAugusto/leakgirls-camsite-downloader#2]
Quit spamming this garbage everywhere.

**Comment by IcaroAugusto** [comment]
No, "spamming" (I don't like this term, I prefer social media marketing) is a legitimate and useful form of marketing, so I will not stop doing it.

It's ironic how some people consider painting huge outdoors, stopping a video (youtube/TV) in the middle to show random ads, stuffing a website/mobile app with ads everywhere etc is acceptable, but telling other people on social media to check out your products is the ultimate evil thing you can do.

**Comment by rivetgeek** [comment]
Oh yagh? Thats why your bots constantly spam reddit trying to defeat COR, eh? Get bent, spammer.
